-- CreateTable
CREATE TABLE `SoldierIntake` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `firstName` VARCHAR(100) NOT NULL,
    `lastName` VARCHAR(100) NOT NULL,
    `citizenId` VARCHAR(50) NOT NULL,
    `birthDate` DATETIME(3) NOT NULL,
    `weightKg` DOUBLE NULL,
    `heightCm` DOUBLE NULL,
    `education` VARCHAR(150) NULL,
    `previousJob` VARCHAR(150) NULL,
    `religion` VARCHAR(100) NULL,
    `canSwim` BOOLEAN NULL,
    `specialSkills` VARCHAR(255) NULL,
    `addressLine` VARCHAR(255) NULL,
    `province` VARCHAR(100) NULL,
    `district` VARCHAR(100) NULL,
    `subdistrict` VARCHAR(100) NULL,
    `postalCode` VARCHAR(20) NULL,
    `email` VARCHAR(191) NULL,
    `phone` VARCHAR(32) NULL,
    `emergencyName` VARCHAR(100) NULL,
    `emergencyPhone` VARCHAR(32) NULL,
    `chronicDiseases` JSON NULL,
    `foodAllergies` JSON NULL,
    `drugAllergies` JSON NULL,
    `medicalNotes` TEXT NULL,
    `idCardImageUrl` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `SoldierIntake_citizenId_idx`(`citizenId`),
    INDEX `SoldierIntake_phone_idx`(`phone`),
    INDEX `SoldierIntake_email_idx`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
